//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArmA.Studio.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArmA.Studio.Properties.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose.
        /// </summary>
        public static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose the UI-Main Config.
        /// </summary>
        public static string ConfigEntrySelectorDialog_Header {
            get {
                return ResourceManager.GetString("ConfigEntrySelectorDialog_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI-Config Selector.
        /// </summary>
        public static string ConfigEntrySelectorDialog_Title {
            get {
                return ResourceManager.GetString("ConfigEntrySelectorDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current document contains unsaved changes.
        ///Do you want to save before close?.
        /// </summary>
        public static string DocumentBase_CloseSaveConfirmation_Body {
            get {
                return ResourceManager.GetString("DocumentBase_CloseSaveConfirmation_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsafed Data.
        /// </summary>
        public static string DocumentBase_CloseSaveConfirmation_Caption {
            get {
                return ResourceManager.GetString("DocumentBase_CloseSaveConfirmation_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing Item....
        /// </summary>
        public static string ExistingItem {
            get {
                return ResourceManager.GetString("ExistingItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &apos;{0}&apos; was not found..
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Folder.
        /// </summary>
        public static string NewFolder {
            get {
                return ResourceManager.GetString("NewFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Item....
        /// </summary>
        public static string NewItem {
            get {
                return ResourceManager.GetString("NewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the current document, there is no config entry available the UI-View could be generated from..
        /// </summary>
        public static string NoConfigPresent_Body {
            get {
                return ResourceManager.GetString("NoConfigPresent_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Config Entry.
        /// </summary>
        public static string NoConfigPresent_Title {
            get {
                return ResourceManager.GetString("NoConfigPresent_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string PanelDisplayName_Properties {
            get {
                return ResourceManager.GetString("PanelDisplayName_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution Explorer.
        /// </summary>
        public static string PanelDisplayName_Solution {
            get {
                return ResourceManager.GetString("PanelDisplayName_Solution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided value contains invalid characters.
        /// </summary>
        public static string SolutionFile_NameContainsInvalidFiles {
            get {
                return ResourceManager.GetString("SolutionFile_NameContainsInvalidFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whoops.
        /// </summary>
        public static string Whoops {
            get {
                return ResourceManager.GetString("Whoops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Existing.
        /// </summary>
        public static string WorkspaceSelectorDialog_Browse {
            get {
                return ResourceManager.GetString("WorkspaceSelectorDialog_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the folder where the project is located..
        /// </summary>
        public static string WorkspaceSelectorDialog_Description {
            get {
                return ResourceManager.GetString("WorkspaceSelectorDialog_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workspace Setup.
        /// </summary>
        public static string WorkspaceSelectorDialog_Header {
            get {
                return ResourceManager.GetString("WorkspaceSelectorDialog_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a valid workspace.
        /// </summary>
        public static string WorkspaceSelectorDialog_NoWorkspaceSelected {
            get {
                return ResourceManager.GetString("WorkspaceSelectorDialog_NoWorkspaceSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workspace Dialog.
        /// </summary>
        public static string WorkspaceSelectorDialog_Title {
            get {
                return ResourceManager.GetString("WorkspaceSelectorDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while loading &apos;{0}&apos;
        ///&apos;{1}&apos; was thrown.
        ///
        ///{2}.
        /// </summary>
        public static string XSHD_Loading_Error_Body {
            get {
                return ResourceManager.GetString("XSHD_Loading_Error_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XSHD Syntax file loading failed..
        /// </summary>
        public static string XSHD_Loading_Error_Title {
            get {
                return ResourceManager.GetString("XSHD_Loading_Error_Title", resourceCulture);
            }
        }
    }
}
